[phases.setup]
nixPkgs = ['bun']

[phases.install]
cmds = ['bun install --frozen-lockfile']

[phases.build]
cmds = ['mkdir -p uploads/evidencias']

[start]
cmd = 'bun run index.js'

[variables]
NODE_ENV = 'production'
